// Job Categories
export const JOBS_CATEGORIES_LIST = 'JOBS_CATEGORIES_LIST'
export const JOBS_CATEGORIES_LOADING = 'JOBS_CATEGORIES_LOADING'
export const JOBS_CATEGORIES_ERROR = 'JOBS_CATEGORIES_ERROR'
