// Job Categories
export const JOBS_CATEGORIES_LIST = 'JOBS_CATEGORIES_LIST'
export const JOBS_CATEGORIES_LOADING = 'JOBS_CATEGORIES_LOADING'
export const JOBS_CATEGORIES_ERROR = 'JOBS_CATEGORIES_ERROR'
export const JOBS_CATEGORIES_BY_ID = 'JOBS_CATEGORIES_ERROR'



//Jobs
export const JOBS_BY_CATEGORIES_LIST = 'JOBS_BY_CATEGORIES_LIST'
export const JOBS_BY_CATEGORIES_LOADING = 'JOBS_BY_CATEGORIES_LOADING'
export const JOBS_BY_CATEGORIES_ERROR = 'JOBS_BY_CATEGORIES_ERROR'
